site_name: Windows API Access From PowerShell
site_url: https://konstantinbelyakov.github.io/powershell-winapi-tutorial/
repo_url: https://github.com/konstantinbelyakov/powershell-winapi-tutorial
edit_uri: edit/main/docs/
nav:
  - index.md
  - Ways to Call a Win32 API Method:
     - win32-approaches/index.md
     - "Approach 1: Add-Type Cmdlet": win32-approaches/add-type.md
     - "Approach 2: Private .NET Method": win32-approaches/private-method.md
     - "Approach 3: Reflection": win32-approaches/reflection.md
  - summary.md
plugins:
  - search
  - i18n:
      docs_structure: suffix
      default_language: en
      languages:
        en:
          name: English
          build: true
          site_name: "Windows API Access From PowerShell"
        ru:
          name: Russian
          build: true
          site_name: "Вызов Windows API из PowerShell"
  - git-revision-date-localized
theme:
    name: material
    font: false
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
      - navigation.indexes
      - navigation.expand
extra_css:
  - extra.css
markdown_extensions:
  - def_list
  - pymdownx.magiclink # auto-link HTML, FTP, and email links https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.keys # add keys like ++ctrl+alt+delete++ # https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed # add tabs https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details # add spoiler (??? note) https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.snippets # insert a file into another markdown file https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.superfences # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - footnotes # https://python-markdown.github.io/extensions/footnotes/
  - tables # https://python-markdown.github.io/extensions/tables/
  - admonition # tips & notes (!!! note) https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list # https://python-markdown.github.io/extensions/attr_list/
  - smarty # converts ASCII dashes, quotes and ellipses to their HTML entity equivalents https://python-markdown.github.io/extensions/smarty/
